### ISSUE TITLE
Book link sends to 404

### ISSUE THREAD

**Issue by sabinevidal** [trailblazer/website#8]
Hi there,

Just found Reform and am experimenting with it as it seems like something that can add a lot of value to what I'm working on. Keen to learn more, but the Trailblazer book referenced in [Populators ](https://trailblazer.to/2.1/docs/reform#reform-populators) redirects to 404, so not sure what book it's referencing. 

I also saw Reform 3/Trailblazer-forms is in the works, is it worth waiting for this before setting up with Reform 2 in a new Rails project?

https://github.com/trailblazer/website/blob/63aac33f604834d9c1be0641a42ac972767f5513/app/concepts/documentation/page/snippet/reform/populators.md.erb#L9C131-L9C131

**Comment by sabinevidal** [comment]
Hey there, thanks so much for your reply! Will give those chapters a read-through. 
Excited to see what's to come with Reform 3! Watched your talk about it and appreciated your approach to redesigning (especially making it harder for people to do weird things 😅)

**Comment by apotonick** [comment]
Try and skip the `:prepopulator` feature, that was a bad design mistake of mine. The `populator`, if used as it was designed to be, still applies, but yeah, in R3 a lot of things got a lot simpler because we deal with different objects "in public", not just one all-mighty form instance. :laughing:
